name: motifscope
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.10
  - pip
  - numpy==1.26.4
  - pandas
  - matplotlib
  - biopython
  - multiprocess
  - umap-learn
  - scikit-learn
  - levenshtein
  - ca-certificates
  - certifi
  - openssl
  - scipy=1.13.0
  - pip:
    - pyabpoa==1.5.3
